source 'https://rubygems.org'

gem 'rails', '4.0.10'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.2'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'

# Specific gem we are testing:
gem 'will_paginate'

# Used for testing
gem 'capybara'
gem 'rspec-rails'
gem 'launchy'
gem 'database_cleaner'
gem 'test_models', git: "git://github.com/upmin/test_models.git"

gemspec :path => '../../'
