source 'https://rubygems.org'

gem 'rails', '3.2.19'

gem 'sqlite3'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'


# Used for testing
gem 'capybara'
gem 'rspec-rails'
gem 'launchy'
gem 'database_cleaner'

gem 'test_models', git: "git://github.com/upmin/test_models.git"

gemspec :path => '../../'
