source 'https://rubygems.org'


gem 'rails', '4.1.6'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'spring',        group: :development


# Used for testing
gem 'capybara'
gem 'rspec-rails'
gem 'launchy'
gem 'database_cleaner'
gem 'test_models', git: "git://github.com/upmin/test_models.git"

gemspec :path => '../../'

