source 'https://rubygems.org'


gem 'rails', '4.2.0.beta1'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0.0.beta1'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'rails-html-sanitizer', '~> 1.0'


group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0.0.beta2'
  gem 'spring'
end


# Specific to 4.2.0.beta1 & upmin-admin
gem 'ransack', github: 'activerecord-hackery/ransack', branch: 'rails-4.2'

# Used for testing
gem 'capybara'
gem 'rspec-rails'
gem 'launchy'
gem 'database_cleaner'
gem 'test_models', git: "git://github.com/upmin/test_models.git"

gemspec :path => '../../'



